### ISSUE TITLE
Does not work on Windows Server 2012R2

### ISSUE THREAD

**Issue by tleclaire** [konradsikorski/smartCAML#49]
Since we are doing om prem dev using Windows Server 2012 R2 as dev Environment, I would like to use it on this OS but I cannot install it since it Needs Windows 10 as prereq.

**Comment by tleclaire** [comment]
Sorry, my bad... I overloked the clicktorun button. ;-)

**Comment by konradsikorski** [comment]
If you have any issue or feedback just contact me :)
